export const actionTypes = {
    FETCH_MOVIES: "FETCH_MOVIES",
    FETCH_CATEGORY: "FETCH_CATEGORY",
    FETCH_WATCH : "FETCH_WATCH",
    ADD_WATCH : "ADD_WATCH",
    REMOVE_WATCH: "REMOVE_WATCH",
    FETCH_FAVORITE : "FETCH_FAVORITE",
    ADD_FAVORITE: "ADD_FAVORITE",
    REMOVE_FAVORITE: "REMOVE_FAVORITE",
    ADD_FRAGMAN : "ADD_FRAGMAN",
    CLEAR_FRAGMAN: "CLEAR_FRAGMAN",
    ADD_VIDEO : "ADD_VIDEO",
}